x-defaults: &defaults
  platform: ${TARGET_PLATFORM:-linux/arm64}

services:
  task-manager:
    <<: *defaults
    build: ./task-manager
    ports:
      - "8001:8000"
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
      - OPENAI_MIDDLE_URL
      - VLM_MODEL
      - TASK_MONITOR_URL
      - MUSIC_HIGHLIGHT_URL
      - MUSIC_CAPTION_URL
  task-monitor:
    <<: *defaults
    build:
      context: ./task-monitor
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production
  music-analysis:
    <<: *defaults
    build: ./music-analysis
    ports:
      - "8101:8000"
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
  music-caption:
    <<: *defaults
    profiles:
      - inference
    build: ./music-caption
    ports:
      - "8102:8000"
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./hf_cache:/root/.cache/huggingface
      - ./music-caption:/app

networks:
  default:
    driver: bridge
